# Generated by Django 3.2.8 on 2021-10-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='vigencia',
            field=models.BooleanField(default=True),
        ),
    ]
